### ISSUE TITLE
tracking notable players

### ISSUE THREAD

**Issue by Turmfalke2** [yasp-dota/yasp#602]
- [x] How are we going to keep it maintained?  Professional players come and go all the time. (Steam API)
- [x] Do we want to fetch full history for these players?  If so, can we automate full history for new players on the list? (automatically done if we fetch complete history)
- [ ] Add a tab for pro players featured?

hi
The general idea is to have a list similar to the cheese list for professional players or highly valued people in the dota scene. The reasoning is that unlike for the normal average player there are usually a few hundred people who interested in their performance.

I got this idea recently when synderen was streaming and asked what his winrate with clockwerk versus earth spirit is. I figured that is easy to find out with yasp, while that is true it doesn't really works if yasp only knows of a small portion of his games.

The question can yasp afford that? Tracking and especially parsing is quite resource intensive.

**Comment by howardchung** [comment]
Yeah this is actually quite possible.  The only tricky part is getting a
list of the ids of "notable" players, since this changes and we would have
to keep it manually maintained.

**Comment by howardchung** [comment]
Maybe we could just stick it in a JSON file and crowdsource it--ask people
to submit pull requests to it or something lol

**Comment by Turmfalke2** [comment]
Figured I might as well start collecting some ids http://pastebin.com/tvXLRvYM
As a warning, it is pretty easy to be biased when put players on that list.
I started taking the players from the top teams according to gosugamers and then added some others that came to mind.
I am not sure 100% sure that all the ids are correct, especially with the chinese players it is kind of tricky, good luck searching for "Q" and "QQQ". Apparently zyf is the same person as yj?

**Comment by howardchung** [comment]
It would be nice to put it in JSON format `{"name":id}`.

Is there a plan to keep the list maintained though?

**Comment by howardchung** [comment]
Automatically parsing those players games: easy since we can just merge this list with the tracked players/donators.

Getting full history for these players: a little trickier since right now we just do it whenever a player logs in.   Might have to write some code that automatically tries the list from time to time and gets full history for any player on it that doesn't have full history yet.

**Comment by Turmfalke2** [comment]
putting it in json format should be easy enough, but what exactly should I put in the name field? Unfortunately players have the tendency of changing their name.
I feel like to keep the list maintained we would need some precise rules for who gets on it.

**Comment by albertcui** [comment]
We should be doing player ID not name.

**Comment by Turmfalke2** [comment]
Oh ok, I failed at the json part. "name" is always going to be "name", thought of it as a bit more fancy csv.

**Comment by Iparke** [comment]
http://pastebin.com/C4m8AcGE

**Comment by Turmfalke2** [comment]
So something like this? http://pastebin.com/9bkhmNH3 name_c wouldn't/shouldn't be used and is more of a comment field to keep the list maintainable.

**Comment by Turmfalke2** [comment]
@Iparke ok, yours is a bit more fancy, I removed the team information since yasp is going to use it anyway and it feels like teams change every 3 weeks anyway.

**Comment by Iparke** [comment]
We can just as easily wrap your's in an array and consume it. I just did mine based on the information available (when I started). Thanks for putting that list together!

**Comment by howardchung** [comment]
Should this go with the values in sources.json or be its own file?

**Comment by albertcui** [comment]
Own file makes it easier to maintain. Sources.json would get even bigger.

**Comment by howardchung** [comment]
I'm thinking we should split up sources into multiple smaller json files and put them in a dir.  Then our constants task can bundle them up neatly and combine it with dota2 jsfeed data to form a nice single constants file.

**Comment by howardchung** [comment]
Easiest to consume format would probably be:
`{1234:"playername",11234:"playername2"}`

Then we can just iterate over the keys in the object and add them to tracked set.

If we want to add additional metadata for each player (such as team), we change from string into a nested object.

**Comment by howardchung** [comment]
however json enforces keys being strings, which is why I suggested doing it the other way around.

array may work too but doesnt come with built in deduplication.

**Comment by howardchung** [comment]
if one of you wants to format it and submit a PR we can merge that in first.

**Comment by howardchung** [comment]
A simpler implementation+potentially useful feature:

Allow users to enter account_ids they want manually tracked.

When we get a track request we would get full match history (as if they had signed in), and parse their matches for the timeout period (currently two weeks).

After the timeout expires users could re-request if they want the player to be tracked again.

**Comment by howardchung** [comment]
I'm thinking just the notable players list.  With the new json split it should be easy to create a new json file and attach it to constants.

**Comment by jford8820** [comment]
I have a SQL database on my home computer with the account id's and names of the players in top 50 teams right before TI5. It's been cleaned by hand and is all English names... created from some nasty scraping of gosugamers and hitting the steam api by league_id, nothing like your beautiful Node parsing. If it sounds useful I'll drop it in a pastebin this weekend.

**Comment by howardchung** [comment]
Sure, we could add it to "notables.json" or something

**Comment by jford8820** [comment]
Okay ill put it on my list.

For bringing this to life maybe a twitter sentiment score for each player to numerically assign importance would work, but that's not so fair to the Chinese players. Possibly a half weibo/half twitter sentiment score. Otherwise it seems like one would have to update a notable players list manually.

**Comment by howardchung** [comment]
If we're going to do this we need to figure out:

* How are we going to keep it maintained?  Professional players come and go all the time.
* Do we want to fetch full history for these players?  If so, can we automate full history for new players on the list?

**Comment by howardchung** [comment]
Apparently there is a handy endpoint for pro players:

https://api.steampowered.com/IDOTA2Fantasy_570/GetProPlayerList/v1?key=

**Comment by howardchung** [comment]
There are 445 players on this list.  Since we're adding FH for everyone (in progress) and this list presumably will be kept updated, we could create a pro player page listing their profiles.  We could also turn on automatic parsing for these players if we wanted.
